import { Account, Budget, Category, SavingsGoal, Subscription, Transaction } from '../types/finance';

export const DEFAULT_CATEGORIES: Category[] = [
  // Expense categories
  { id: 'cat_housing', name: 'Housing & Rent', type: 'expense', icon: 'Home', color: '#6366f1', isDefault: true },
  { id: 'cat_food', name: 'Food & Dining', type: 'expense', icon: 'Utensils', color: '#f97316', isDefault: true },
  { id: 'cat_groceries', name: 'Groceries', type: 'expense', icon: 'ShoppingCart', color: '#10b981', isDefault: true },
  { id: 'cat_transport', name: 'Transportation', type: 'expense', icon: 'Car', color: '#06b6d4', isDefault: true },
  { id: 'cat_utilities', name: 'Bills & Utilities', type: 'expense', icon: 'Zap', color: '#eab308', isDefault: true },
  { id: 'cat_shopping', name: 'Shopping & Gear', type: 'expense', icon: 'ShoppingBag', color: '#ec4899', isDefault: true },
  { id: 'cat_entertainment', name: 'Entertainment & Subs', type: 'expense', icon: 'Film', color: '#8b5cf6', isDefault: true },
  { id: 'cat_health', name: 'Health & Medical', type: 'expense', icon: 'HeartPulse', color: '#ef4444', isDefault: true },
  { id: 'cat_travel', name: 'Travel & Vacation', type: 'expense', icon: 'Plane', color: '#14b8a6', isDefault: true },
  { id: 'cat_education', name: 'Education & Books', type: 'expense', icon: 'GraduationCap', color: '#3b82f6', isDefault: true },
  { id: 'cat_personal', name: 'Personal Care', type: 'expense', icon: 'Smile', color: '#f43f5e', isDefault: true },
  { id: 'cat_investments', name: 'Investments', type: 'expense', icon: 'TrendingUp', color: '#22c55e', isDefault: true },
  { id: 'cat_other_exp', name: 'Other Expense', type: 'expense', icon: 'MoreHorizontal', color: '#64748b', isDefault: true },

  // Income categories
  { id: 'cat_salary', name: 'Primary Salary', type: 'income', icon: 'Briefcase', color: '#10b981', isDefault: true },
  { id: 'cat_freelance', name: 'Freelance & Side Gig', type: 'income', icon: 'Laptop', color: '#06b6d4', isDefault: true },
  { id: 'cat_invest_return', name: 'Dividends & Returns', type: 'income', icon: 'BarChart2', color: '#8b5cf6', isDefault: true },
  { id: 'cat_cashback', name: 'Cashback & Rewards', type: 'income', icon: 'Gift', color: '#f59e0b', isDefault: true },
  { id: 'cat_other_inc', name: 'Other Income', type: 'income', icon: 'Coins', color: '#64748b', isDefault: true },
];

export const DEFAULT_ACCOUNTS: Account[] = [
  { id: 'acc_checking', name: 'Main Checking', type: 'bank', balance: 4850.50, currency: 'USD', color: '#3b82f6', icon: 'Building2', accountNumberMasked: '•• 4912' },
  { id: 'acc_savings', name: 'High Yield Savings', type: 'savings', balance: 12400.00, currency: 'USD', color: '#10b981', icon: 'Vault', accountNumberMasked: '•• 8301' },
  { id: 'acc_credit', name: 'Sapphire Credit Card', type: 'credit_card', balance: -640.20, currency: 'USD', color: '#8b5cf6', icon: 'CreditCard', accountNumberMasked: '•• 9023' },
  { id: 'acc_cash', name: 'Cash Wallet', type: 'cash', balance: 180.00, currency: 'USD', color: '#f59e0b', icon: 'Wallet' },
  { id: 'acc_crypto', name: 'Crypto & Assets', type: 'crypto', balance: 3250.00, currency: 'USD', color: '#ec4899', icon: 'Bitcoin' },
];

function getRelativeDateString(daysAgo: number): string {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString().split('T')[0];
}

export function generateSampleTransactions(): Transaction[] {
  return [
    {
      id: 'tx_1',
      type: 'income',
      amount: 4500.00,
      categoryId: 'cat_salary',
      accountId: 'acc_checking',
      date: getRelativeDateString(1),
      merchant: 'Acme Corp Tech Payroll',
      description: 'Bi-weekly tech engineer salary',
      tags: ['salary', 'direct-deposit'],
      createdAt: new Date().toISOString(),
    },
    {
      id: 'tx_2',
      type: 'expense',
      amount: 1450.00,
      categoryId: 'cat_housing',
      accountId: 'acc_checking',
      date: getRelativeDateString(2),
      merchant: 'Skyline Apartments',
      description: 'Monthly apartment rent & amenities',
      tags: ['rent', 'fixed'],
      isRecurring: true,
      recurringId: 'sub_rent',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'tx_3',
      type: 'expense',
      amount: 142.50,
      categoryId: 'cat_groceries',
      accountId: 'acc_credit',
      date: getRelativeDateString(2),
      merchant: 'Whole Foods Market',
      description: 'Weekly organic pantry & produce',
      tags: ['groceries', 'food'],
      createdAt: new Date().toISOString(),
    },
    {
      id: 'tx_4',
      type: 'expense',
      amount: 48.75,
      categoryId: 'cat_food',
      accountId: 'acc_credit',
      date: getRelativeDateString(3),
      merchant: 'Artisan Ramen & Noodle Bar',
      description: 'Dinner with coworkers',
      tags: ['dining', 'social'],
      createdAt: new Date().toISOString(),
    },
    {
      id: 'tx_5',
      type: 'expense',
      amount: 19.99,
      categoryId: 'cat_entertainment',
      accountId: 'acc_credit',
      date: getRelativeDateString(4),
      merchant: 'Netflix Premium 4K',
      description: 'Monthly 4K streaming plan',
      isRecurring: true,
      recurringId: 'sub_netflix',
      tags: ['subscription'],
      createdAt: new Date().toISOString(),
    },
    {
      id: 'tx_6',
      type: 'expense',
      amount: 65.00,
      categoryId: 'cat_transport',
      accountId: 'acc_credit',
      date: getRelativeDateString(5),
      merchant: 'Shell Gas Station',
      description: 'Full vehicle fuel tank refill',
      tags: ['transport', 'commute'],
      createdAt: new Date().toISOString(),
    },
    {
      id: 'tx_7',
      type: 'income',
      amount: 850.00,
      categoryId: 'cat_freelance',
      accountId: 'acc_checking',
      date: getRelativeDateString(6),
      merchant: 'Design Studio Client',
      description: 'Frontend dashboard UI consulting',
      tags: ['freelance', 'side-income'],
      createdAt: new Date().toISOString(),
    },
    {
      id: 'tx_8',
      type: 'expense',
      amount: 110.00,
      categoryId: 'cat_utilities',
      accountId: 'acc_checking',
      date: getRelativeDateString(7),
      merchant: 'Clean Energy & Power',
      description: 'Monthly electricity and climate bill',
      isRecurring: true,
      tags: ['utilities'],
      createdAt: new Date().toISOString(),
    },
    {
      id: 'tx_9',
      type: 'expense',
      amount: 89.90,
      categoryId: 'cat_shopping',
      accountId: 'acc_credit',
      date: getRelativeDateString(8),
      merchant: 'Amazon Marketplace',
      description: 'Ergonomic mouse & desk accessories',
      tags: ['office', 'gear'],
      createdAt: new Date().toISOString(),
    },
    {
      id: 'tx_10',
      type: 'expense',
      amount: 35.00,
      categoryId: 'cat_health',
      accountId: 'acc_credit',
      date: getRelativeDateString(10),
      merchant: 'Apex Fitness & Gym',
      description: 'Monthly gym membership',
      isRecurring: true,
      recurringId: 'sub_gym',
      tags: ['fitness'],
      createdAt: new Date().toISOString(),
    },
    {
      id: 'tx_11',
      type: 'expense',
      amount: 8.50,
      categoryId: 'cat_food',
      accountId: 'acc_cash',
      date: getRelativeDateString(11),
      merchant: 'Blue Bottle Specialty Coffee',
      description: 'Morning Oat Latte',
      tags: ['coffee'],
      createdAt: new Date().toISOString(),
    },
    {
      id: 'tx_12',
      type: 'expense',
      amount: 75.00,
      categoryId: 'cat_utilities',
      accountId: 'acc_checking',
      date: getRelativeDateString(12),
      merchant: 'Fiber Gigabit Internet',
      description: 'Monthly high-speed fiber internet',
      isRecurring: true,
      tags: ['utilities'],
      createdAt: new Date().toISOString(),
    },
    {
      id: 'tx_13',
      type: 'expense',
      amount: 125.40,
      categoryId: 'cat_groceries',
      accountId: 'acc_credit',
      date: getRelativeDateString(14),
      merchant: 'Trader Joe\'s',
      description: 'Bi-weekly groceries & snacks',
      tags: ['groceries'],
      createdAt: new Date().toISOString(),
    },
    {
      id: 'tx_14',
      type: 'income',
      amount: 125.00,
      categoryId: 'cat_invest_return',
      accountId: 'acc_savings',
      date: getRelativeDateString(15),
      merchant: 'Vanguard Index Dividends',
      description: 'Quarterly ETF dividend payout',
      tags: ['investing', 'passive'],
      createdAt: new Date().toISOString(),
    },
    {
      id: 'tx_15',
      type: 'expense',
      amount: 500.00,
      categoryId: 'cat_investments',
      accountId: 'acc_checking',
      date: getRelativeDateString(16),
      merchant: 'Index Fund Auto-Invest',
      description: 'Monthly S&P 500 DCA contribution',
      tags: ['investment', 'wealth'],
      createdAt: new Date().toISOString(),
    },
    {
      id: 'tx_16',
      type: 'expense',
      amount: 52.00,
      categoryId: 'cat_food',
      accountId: 'acc_credit',
      date: getRelativeDateString(18),
      merchant: 'Taco Craft & Grill',
      description: 'Weekend lunch with family',
      tags: ['dining'],
      createdAt: new Date().toISOString(),
    },
    {
      id: 'tx_17',
      type: 'expense',
      amount: 14.99,
      categoryId: 'cat_entertainment',
      accountId: 'acc_credit',
      date: getRelativeDateString(20),
      merchant: 'Spotify Music Duo',
      description: 'Music streaming subscription',
      isRecurring: true,
      recurringId: 'sub_spotify',
      tags: ['subscription', 'music'],
      createdAt: new Date().toISOString(),
    },
    {
      id: 'tx_18',
      type: 'expense',
      amount: 22.00,
      categoryId: 'cat_transport',
      accountId: 'acc_credit',
      date: getRelativeDateString(22),
      merchant: 'City Metro Transit Card',
      description: 'Subway reload passes',
      tags: ['transit'],
      createdAt: new Date().toISOString(),
    },
  ];
}

export const DEFAULT_BUDGETS: Budget[] = [
  { id: 'bgt_housing', categoryId: 'cat_housing', amount: 1500, period: 'monthly', alertThreshold: 90 },
  { id: 'bgt_food', categoryId: 'cat_food', amount: 350, period: 'monthly', alertThreshold: 80 },
  { id: 'bgt_groceries', categoryId: 'cat_groceries', amount: 450, period: 'monthly', alertThreshold: 80 },
  { id: 'bgt_transport', categoryId: 'cat_transport', amount: 200, period: 'monthly', alertThreshold: 80 },
  { id: 'bgt_utilities', categoryId: 'cat_utilities', amount: 250, period: 'monthly', alertThreshold: 85 },
  { id: 'bgt_shopping', categoryId: 'cat_shopping', amount: 250, period: 'monthly', alertThreshold: 75 },
  { id: 'bgt_entertainment', categoryId: 'cat_entertainment', amount: 150, period: 'monthly', alertThreshold: 80 },
  { id: 'bgt_health', categoryId: 'cat_health', amount: 120, period: 'monthly', alertThreshold: 80 },
  { id: 'bgt_investments', categoryId: 'cat_investments', amount: 600, period: 'monthly', alertThreshold: 95 },
];

export const DEFAULT_GOALS: SavingsGoal[] = [
  {
    id: 'goal_emergency',
    name: '6-Month Emergency Safety Fund',
    targetAmount: 15000,
    currentAmount: 11200,
    targetDate: '2026-12-31',
    color: '#10b981',
    icon: 'ShieldCheck',
    notes: 'Safe cushion for 6 months living expenses stored in HYSA',
    category: 'Safety',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'goal_japan',
    name: 'Trip to Tokyo & Kyoto, Japan',
    targetAmount: 3800,
    currentAmount: 2450,
    targetDate: '2026-10-15',
    color: '#ec4899',
    icon: 'Plane',
    notes: 'Flights, Ryokan stay, and culinary exploration in Japan',
    category: 'Travel',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'goal_macbook',
    name: 'M4 Max Developer Workstation',
    targetAmount: 2800,
    currentAmount: 2100,
    targetDate: '2026-09-30',
    color: '#3b82f6',
    icon: 'Laptop',
    notes: 'Upgrade development machine for software projects',
    category: 'Gear',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'goal_invest',
    name: 'Yearly Roth IRA Max Out',
    targetAmount: 7000,
    currentAmount: 4800,
    targetDate: '2026-12-31',
    color: '#8b5cf6',
    icon: 'TrendingUp',
    notes: 'Annual tax-advantaged retirement allocation',
    category: 'Investing',
    createdAt: new Date().toISOString(),
  },
];

export const DEFAULT_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub_rent',
    name: 'Skyline Apartment Rent',
    amount: 1450.00,
    billingCycle: 'monthly',
    nextBillingDate: getRelativeDateString(-25),
    categoryId: 'cat_housing',
    accountId: 'acc_checking',
    status: 'active',
    color: '#6366f1',
    reminderDaysBefore: 3,
  },
  {
    id: 'sub_netflix',
    name: 'Netflix Premium 4K',
    amount: 19.99,
    billingCycle: 'monthly',
    nextBillingDate: getRelativeDateString(-14),
    categoryId: 'cat_entertainment',
    accountId: 'acc_credit',
    status: 'active',
    color: '#ef4444',
    websiteUrl: 'https://netflix.com',
    reminderDaysBefore: 2,
  },
  {
    id: 'sub_spotify',
    name: 'Spotify Premium Duo',
    amount: 14.99,
    billingCycle: 'monthly',
    nextBillingDate: getRelativeDateString(-8),
    categoryId: 'cat_entertainment',
    accountId: 'acc_credit',
    status: 'active',
    color: '#10b981',
    websiteUrl: 'https://spotify.com',
    reminderDaysBefore: 1,
  },
  {
    id: 'sub_gym',
    name: 'Apex Fitness Center',
    amount: 35.00,
    billingCycle: 'monthly',
    nextBillingDate: getRelativeDateString(-12),
    categoryId: 'cat_health',
    accountId: 'acc_credit',
    status: 'active',
    color: '#f97316',
    reminderDaysBefore: 2,
  },
  {
    id: 'sub_github',
    name: 'GitHub Copilot & Pro',
    amount: 10.00,
    billingCycle: 'monthly',
    nextBillingDate: getRelativeDateString(-5),
    categoryId: 'cat_education',
    accountId: 'acc_credit',
    status: 'active',
    color: '#06b6d4',
    websiteUrl: 'https://github.com',
    reminderDaysBefore: 2,
  },
  {
    id: 'sub_cloud',
    name: 'iCloud 2TB Storage',
    amount: 9.99,
    billingCycle: 'monthly',
    nextBillingDate: getRelativeDateString(-18),
    categoryId: 'cat_utilities',
    accountId: 'acc_credit',
    status: 'active',
    color: '#3b82f6',
    reminderDaysBefore: 1,
  }
];
